yolov7-base:
  type: yolov7
  weights_path: "weights/best.pt"
  dataset_path: "data/validation_set"
  class_names: ['paja', 'suciedad']
  feature_layers: # Nombres o índices de capas interesantes para este modelo
    backbone (Capa 10): 10
    neck (Capa 50): 50
    head_small (Capa 102): 102
    head_medium (Capa 103): 103
    head_large (Capa 104): 104
  target_layer: 30

yolov8-nano:
  type: yolov8
  weights_path: "weights/best.pt"
  dataset_path: "data/validation_set"
  class_names: ['suciedad', 'paja']
  feature_layers: # En v8, los nombres de las capas pueden ser diferentes
    backbone: 'model.4' # Ejemplo, necesitarás investigar la arquitectura
    neck: 'model.15'
    head: 'model.22'

# y cuando salga yolov11...
# yolov11-small:
#   type: yolov11
#   ...etc